server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /service-a

logging:
  level:
    root: INFO

spring:
  application:
    name: '@project.artifactId@'
    version: '@project.version@'
  zipkin:
    baseUrl: ${TRACES_ENDPOINT}
  sleuth:
    sampler:
      probability: 1.0
      
management:
  metrics:
    tags:
      application: '@project.artifactId@'
  endpoints:
    web:
      exposure:
        include: 'health,info,prometheus'
        exclude: env
      cors:
        allowed-origins:
        - '*'
        allowed-methods:
        - GET
        - OPTIONS
        allowed-headers:
        - '*'

service-b:
  pedido:
    url: ${SERVICE_B_PEDIDO_URL}
  user:
    url: ${SERVICE_B_USER_URL}
  users:
    url: ${SERVICE_B_USERS_URL}
    
service-k1:
  pedido:
    url: ${SERVICE_K1_PEDIDO_URL}
  user:
    topic:
      create: 
        url: ${SERVICE_K1_USER_TOPIC_CREATE_URL}
  tramit:
    topic:
      create:
        url: ${SERVICE_K1_TRAMIT_TOPIC_CREATE_URL}