server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /service-a

logging:
  level:
    root: INFO

spring:
  application:
    name: '@project.artifactId@'
    version: '@project.version@'
  zipkin:
    baseUrl: http://jaeger-collector.istio-system.svc.cluster.local:9411
  sleuth:
    sampler:
      probability: 1.0
      
management:
  metrics:
    tags:
      application: '@project.artifactId@'
  endpoints:
    web:
      exposure:
        include: 'health,info,prometheus'
        exclude: env

service-b:
  url: http://service-b-svc/service-b/hello/direct
  user:
    url: http://service-b-svc/service-b/user/1
  users:
    url: http://service-b-svc/service-b/user/users
    
service-k1:
  user:
    topic:
      create: 
        url: http://service-k-svc/service-k1/user/create
  tramit:
    topic:
      create:
        url: http://service-k-svc/service-k1/tramit/create