---
apiVersion: v1
kind: Service
metadata:
  name: service-a-svc
  namespace: prod  
  labels:
    app: service-a
    k8s-app: service-a
    version: v1
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http-port
    protocol: TCP
  selector:
    app: service-a
    k8s-app: service-a
    version: v1
